# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: O:/ENGS128/lab3/lab3.srcs/sources_1/bd/axi_stream_bd/ip/axi_stream_bd_axis_fir_0_0/axi_stream_bd_axis_fir_0_0.xci
# IP: The module: 'axi_stream_bd_axis_fir_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: O:/ENGS128/lab3/lab3.srcs/sources_1/ip/fir_bsf_0/fir_bsf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_bsf_0 || ORIG_REF_NAME==fir_bsf_0} -quiet] -quiet

# IP: O:/ENGS128/lab3/lab3.srcs/sources_1/ip/fir_bpf_0/fir_bpf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_bpf_0 || ORIG_REF_NAME==fir_bpf_0} -quiet] -quiet

# IP: O:/ENGS128/lab3/lab3.srcs/sources_1/ip/fir_hpf_0/fir_hpf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_hpf_0 || ORIG_REF_NAME==fir_hpf_0} -quiet] -quiet

# IP: O:/ENGS128/lab3/lab3.srcs/sources_1/ip/fir_lpf_0_1/fir_lpf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_lpf_0 || ORIG_REF_NAME==fir_lpf_0} -quiet] -quiet

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/ip/fir_bsf_0/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_bsf_0 || ORIG_REF_NAME==fir_bsf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/ip/fir_bpf_0/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_bpf_0 || ORIG_REF_NAME==fir_bpf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/ip/fir_hpf_0/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_hpf_0 || ORIG_REF_NAME==fir_hpf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/ip/fir_lpf_0_1/constraints/fir_compiler_v7_2.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_lpf_0 || ORIG_REF_NAME==fir_lpf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/bd/axi_stream_bd/ip/axi_stream_bd_axis_fir_0_0/axi_stream_bd_axis_fir_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_stream_bd_axis_fir_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: O:/ENGS128/lab3/lab3.srcs/sources_1/bd/axi_stream_bd/ip/axi_stream_bd_axis_fir_0_0/axi_stream_bd_axis_fir_0_0.xci
# IP: The module: 'axi_stream_bd_axis_fir_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: O:/ENGS128/lab3/lab3.srcs/sources_1/ip/fir_bsf_0/fir_bsf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_bsf_0 || ORIG_REF_NAME==fir_bsf_0} -quiet] -quiet

# IP: O:/ENGS128/lab3/lab3.srcs/sources_1/ip/fir_bpf_0/fir_bpf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_bpf_0 || ORIG_REF_NAME==fir_bpf_0} -quiet] -quiet

# IP: O:/ENGS128/lab3/lab3.srcs/sources_1/ip/fir_hpf_0/fir_hpf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_hpf_0 || ORIG_REF_NAME==fir_hpf_0} -quiet] -quiet

# IP: O:/ENGS128/lab3/lab3.srcs/sources_1/ip/fir_lpf_0_1/fir_lpf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_lpf_0 || ORIG_REF_NAME==fir_lpf_0} -quiet] -quiet

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/ip/fir_bsf_0/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_bsf_0 || ORIG_REF_NAME==fir_bsf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/ip/fir_bpf_0/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_bpf_0 || ORIG_REF_NAME==fir_bpf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/ip/fir_hpf_0/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_hpf_0 || ORIG_REF_NAME==fir_hpf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/ip/fir_lpf_0_1/constraints/fir_compiler_v7_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_lpf_0 || ORIG_REF_NAME==fir_lpf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: o:/ENGS128/lab3/lab3.gen/sources_1/bd/axi_stream_bd/ip/axi_stream_bd_axis_fir_0_0/axi_stream_bd_axis_fir_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_stream_bd_axis_fir_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
